services:
  mariadb:
    ports:
      - "3306:3306"
    networks:
      - default

  svws:
    image: svwsnrw/svws-server:1.2.1
    ports:
      - "8443:8443"
    networks:
      - default
    environment:
      SVWS_TLS_CERT_CN: localhost
      SVWS_TLS_CERT_OU: Test
      SVWS_TLS_CERT_O: Test
      SVWS_TLS_CERT_L: Test
      SVWS_TLS_CERT_S: NRW
      SVWS_TLS_CERT_C: DE

  mariadb-backup:
    networks:
      - default

networks:
  default:
    driver: bridge
  coolify:
    external: false
    driver: bridge
